Repository microsoft/xdp-for-windows, pull requests merged in 2023-06, with the labels that each got.

#264 Force eBPF powershell job cleanup
  tools/setup.ps1
Labels: bug

#262 Fix the only AzWatson bugcheck in the last 7 days
  src/xdplwf/ec.c
Labels: bug

#281 consistently use xdp.cpp.default.props
  samples/rxfilter/rxfilter.vcxproj
  src/nmr/nmr.vcxproj
  src/pollshim/pollshim.vcxproj
  src/rtl/rtl.vcxproj
  src/xdp/xdp.vcxproj
  src/xdpapi/xdpapi.vcxproj
  src/xdpetw/xdpetw.vcxproj
  src/xdplwf/xdplwf.vcxproj
  test/build_headers/ddk/c/cddkheaders.vcxproj
  test/build_headers/ddk/cpp/cppddkheaders.vcxproj
  test/build_headers/sdk/c/csdkheaders.vcxproj
  test/build_headers/sdk/cpp/cppsdkheaders.vcxproj
  test/common/lib/bounce/bounce.vcxproj
  test/common/lib/fnio/fnio.vcxproj
  test/common/lib/util/util.vcxproj
  test/fakendis/fndis.vcxproj
  test/functional/lib/xdptests.vcxproj
  test/functional/lwf/lib/xdpfnlwfapi.vcxproj
  test/functional/lwf/sys/xdpfnlwf.vcxproj
  test/functional/mp/lib/xdpfnmpapi.vcxproj
  test/functional/mp/sys/generic/xdpfnmpgeneric.vcxproj
  test/functional/mp/sys/native/xdpfnmpnative.vcxproj
  test/functional/mp/sys/xdpfnmp.vcxproj
  test/functional/taef/xdpfunctionaltests.vcxproj
  test/pktcmd/pktcmd.vcxproj
  test/pkthlp/km/pkthlp_km.vcxproj
  test/pkthlp/um/pkthlp_um.vcxproj
  test/rssconfig/rssconfig.vcxproj
  test/xdpmp/xdpmp.vcxproj
  test/xskbench/xskbench.vcxproj
  xdp.cpp.props
Labels: build

#282 Add downlevel VS2019 build
  .github/workflows/ci.yml
Labels: build

#287 Link to Perf Dashboard
  readme.md
Labels: documentation

#295 Add simple AF_XDP sample
  samples/xskfwd/xskfwd.c
  samples/xskfwd/xskfwd.vcxproj
  tools/create-devkit.ps1
  xdp.sln
Labels: documentation

#298 Move .props files to src directory
  docs/release.md
  samples/rxfilter/rxfilter.vcxproj
  samples/xskfwd/xskfwd.vcxproj
  src/nmr/nmr.vcxproj
  src/pollshim/pollshim.vcxproj
  src/rtl/rtl.vcxproj
  src/xdp.cpp.default.props
  src/xdp.cpp.kernel.props
  src/xdp.cpp.props
  src/xdp.cpp.user.props
  src/xdp.props
  src/xdp/xdp.vcxproj
  src/xdpapi/xdpapi.vcxproj
  src/xdpcfg/xdpcfg.vcxproj
  src/xdpetw/xdpetw.vcxproj
  src/xdplwf/xdplwf.vcxproj
  test/bpf/bpf.vcxproj
  test/build_headers/ddk/c/cddkheaders.vcxproj
  test/build_headers/ddk/cpp/cppddkheaders.vcxproj
  test/build_headers/sdk/c/csdkheaders.vcxproj
  test/build_headers/sdk/cpp/cppsdkheaders.vcxproj
  test/common/lib/bounce/bounce.vcxproj
  test/common/lib/fnio/fnio.vcxproj
  test/common/lib/util/util.vcxproj
  test/fakendis/fndis.vcxproj
  test/functional/lib/xdptests.vcxproj
  test/functional/lwf/lib/xdpfnlwfapi.vcxproj
  test/functional/lwf/sys/xdpfnlwf.vcxproj
  test/functional/mp/lib/xdpfnmpapi.vcxproj
  test/functional/mp/sys/generic/xdpfnmpgeneric.vcxproj
  test/functional/mp/sys/native/xdpfnmpnative.vcxproj
  test/functional/mp/sys/xdpfnmp.vcxproj
  test/functional/taef/xdpfunctionaltests.vcxproj
  test/pktcmd/pktcmd.vcxproj
  test/pkthlp/km/pkthlp_km.vcxproj
  test/pkthlp/um/pkthlp_um.vcxproj
  test/rssconfig/rssconfig.vcxproj
  test/spinxsk/spinxsk.vcxproj
  test/xdpmp/xdpmp.vcxproj
  test/xskbench/xskbench.vcxproj
  tools/create-devkit.ps1
  tools/create-runtime-kit.ps1
Labels: build

#316 Fix perf runs with MSI
  tools/setup.ps1
  tools/xskperf.ps1
  tools/xskperfsuite.ps1
Labels: bug
