Repository microsoft/xdp-for-windows, pull requests merged in 2024-06, with the labels that each got.

#525 perf test: continue past errors during cleanup
  tools/two-machine-perf.ps1
Labels: test gap

#531 fix new afxdp.h nameless struct warning
  published/external/afxdp.h
Labels: bug, build

#532 don't publish symbols in github builds
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: build

#534 clean up pending NBLs in FNMP and FNLWF using RAII
  src/xdp.props
  test/functional/lib/tests.cpp
  tools/common.ps1
Labels: bug, tests

#535 run stress tests on Windows prerelease
  .github/workflows/ci.yml
Labels: actions, tests

#538 Fix retry logic during Rename-NetAdapter
  tools/setup.ps1
Labels: bug, tests

#540 Prevent TCP connections lingering beyond intended lifetime
  test/functional/lib/tests.cpp
Labels: bug, tests

#539 Reduce spinxsk variance
  tools/spinxsk.ps1
Labels: bug, tests

#542 Set test attribute for prerelease feature tests
  test/functional/taef/tests.cpp
Labels: tests

#543 spinxsk: ignore success threshold in final short iteration
  tools/spinxsk.ps1
Labels: bug, tests

#554 fix build for GenericRxEbpfFragments
  test/functional/lib/tests.cpp
Labels: bug, build

#550 don't run prerelease tests downlevel, part 2
  .github/workflows/ci.yml
  test/functional/taef/tests.cpp
  tools/functional.ps1
Labels: tests

#552 update filtering logic for prerelease tests
  test/functional/taef/tests.cpp
Labels: tests

#555 Actually require all CI jobs succeed
  .github/workflows/ci.yml
Labels: actions

#559 deny all permissions for completion check
  .github/workflows/ci.yml
Labels: actions, security

#558 Add xdp-onebranch.sln
  src/xdp.cpp.kernel.props
  src/xdpetw/xdpetw.vcxproj
  src/xdppcw/xdppcw.vcxproj
  xdp-onebranch.sln
Labels: build

#549 Fix direct OID completion
  src/xdp.props
  src/xdplwf/oid.c
  test/functional/lib/tests.cpp
  test/functional/lib/tests.h
  test/functional/taef/tests.cpp
  tools/common.ps1
Labels: bug

#560 improve reliability of GenericTxMtu test
  test/functional/lib/tests.cpp
Labels: bug, tests

#566 convert CI agent provisioning scripts to manifests
  .azure/agents/functional.json
  .azure/agents/spinxsk.json
  .azure/scripts/agent-functionaltest/Setup.ps1
  .azure/scripts/agent-spinxsktest/Setup.ps1
  .github/workflows/ci.yml
  tools/prepare-machine.ps1
Labels: tests

#568 consume wnt as nuget
  src/xdp.props
  src/xdp/packages.config
  test/functional/lib/xdptests.vcxproj
  test/functional/taef/xdpfunctionaltests.vcxproj
  test/pktcmd/pktcmd.vcxproj
  test/pktfuzz/pktfuzz.vcxproj
  test/xdpmp/xdpmp.vcxproj
  tools/common.ps1
  tools/prepare-machine.ps1
Labels: dependencies, build

#569 MSI: relocate license and use consistent filename case
  src/xdpinstaller/license.rtf
  src/xdpinstaller/product.wxs
  src/xdpinstaller/xdpinstaller.wixproj
Labels: build

#570 Update instructions in development.md
  docs/development.md
Labels: documentation

#565 Use FnSock from win-net-test in functional test
  test/functional/lib/tests.cpp
  test/functional/taef/xdpfunctionaltests.vcxproj
  tools/functional.ps1
  tools/setup.ps1
  tools/xdptrace.wprp
Labels: tests

#573 fix ebpf struct version validation
  src/xdp/program.c
Labels: bug, ebpf
