Repository microsoft/xdp-for-windows, pull requests merged in 2025-04, with the labels that each got.

#817 add IO completion watchdogs to xskbench
  test/xskbench/xskbench.c
Labels: tests, performance

#825 Fix a race condition in xdp receive path in low resources scenario
  src/xdpetw/xdpetw.man
  src/xdplwf/recv.c
  src/xdppcw/inc/xdppcw.h
  src/xdppcw/xdppcw.man
Labels: diagnostics

#759 clean up of ebpf 0.18/0.20 bug mitigations
  published/external/xdp/ebpfhook.h
  src/xdp.props
  tools/prepare-machine.ps1
Labels: dependencies, build, ebpf

#833 Use central package management for nuget
  Directory.Packages.props
  src/xdp.props
  src/xdpinstaller/xdpinstaller.wixproj
Labels: build

#756 validate onebranch-style builds for arm64, too
  .github/workflows/ci.yml
Labels: build, tests, github_actions
